In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5917, 5063, 8833, 8700],
 [5917, 5063, 8833, 3111],
 [5917, 6117, 8833, 4643],
 [6125, 6202, 1963, 3810, 6350],
 [6125, 6202, 1963, 3810, 3441],
 [3880, 5917, 3345, 8833, 2086],
 [5957, 2855, 8705, 3810]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5917 5063 8833 8700]
 [   0    0    0    0 5917 5063 8833 3111]
 [   0    0    0    0 5917 6117 8833 4643]
 [   0    0    0 6125 6202 1963 3810 6350]
 [   0    0    0 6125 6202 1963 3810 3441]
 [   0    0    0 3880 5917 3345 8833 2086]
 [   0    0    0    0 5957 2855 8705 3810]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\SIMPLE-RNN-IMDB\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step


array([[[-1.48200393e-02,  2.23739855e-02, -4.51624990e-02,
         -3.79488356e-02,  3.48762311e-02, -4.11393531e-02,
          2.26203352e-03, -2.30218656e-02, -3.34889442e-02,
         -2.99836751e-02],
        [-1.48200393e-02,  2.23739855e-02, -4.51624990e-02,
         -3.79488356e-02,  3.48762311e-02, -4.11393531e-02,
          2.26203352e-03, -2.30218656e-02, -3.34889442e-02,
         -2.99836751e-02],
        [-1.48200393e-02,  2.23739855e-02, -4.51624990e-02,
         -3.79488356e-02,  3.48762311e-02, -4.11393531e-02,
          2.26203352e-03, -2.30218656e-02, -3.34889442e-02,
         -2.99836751e-02],
        [-1.48200393e-02,  2.23739855e-02, -4.51624990e-02,
         -3.79488356e-02,  3.48762311e-02, -4.11393531e-02,
          2.26203352e-03, -2.30218656e-02, -3.34889442e-02,
         -2.99836751e-02],
        [-1.47343278e-02,  5.06293774e-03,  3.13385613e-02,
          2.41501816e-02, -1.82732344e-02,  2.00704075e-02,
          4.69013788e-02,  4.86821048e-02, -4.291609

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5917, 5063, 8833, 8700], dtype=int32)

In [16]:
model.predict(np.array(embedded_docs[0]).reshape(1, sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[-1.4820039e-02,  2.2373985e-02, -4.5162499e-02, -3.7948836e-02,
          3.4876231e-02, -4.1139353e-02,  2.2620335e-03, -2.3021866e-02,
         -3.3488944e-02, -2.9983675e-02],
        [-1.4820039e-02,  2.2373985e-02, -4.5162499e-02, -3.7948836e-02,
          3.4876231e-02, -4.1139353e-02,  2.2620335e-03, -2.3021866e-02,
         -3.3488944e-02, -2.9983675e-02],
        [-1.4820039e-02,  2.2373985e-02, -4.5162499e-02, -3.7948836e-02,
          3.4876231e-02, -4.1139353e-02,  2.2620335e-03, -2.3021866e-02,
         -3.3488944e-02, -2.9983675e-02],
        [-1.4820039e-02,  2.2373985e-02, -4.5162499e-02, -3.7948836e-02,
          3.4876231e-02, -4.1139353e-02,  2.2620335e-03, -2.3021866e-02,
         -3.3488944e-02, -2.9983675e-02],
        [-1.4734328e-02,  5.0629377e-03,  3.1338561e-02,  2.4150182e-02,
         -1.8273234e-02,  2.0070408e-02,  4.6901379e-02,  4.8682105e-02,
         -4.2916097e-02, -3.3728682e-02],
        [-1.9125938e-03,  1.2417577e-02, -3.5775770e-02,  4.